default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: blog-posting-system/development

test:
  <<: *default
  database: blog-posting-system/test

production:
  <<: *default
  database: blog-posting-system/production
